version: '3.7'

services:

  document:
    build:
      context: ./services/documents
      dockerfile: Dockerfile-dev
    volumes:
      - './services/documents:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@document-db:5432/documents_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@document-db:5432/documents_test
    depends_on:  # nuevo
      - document-db

  document-db:  # nuevo
    build:
      context: ./services/documents/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-dev
    restart: always
    ports:
      - 80:80
    depends_on:
      - document